export const demoUser = {
  id: "demo-user",
  full_name: "Demo Learner",
  role: "student",
};

export const demoCourses = [
  {
    id: "1",
    title: "Mathematics Grade 10",
    subject: "Math",
    difficulty: "Intermediate",
    instructor_name: "Ms. Santos",
    emoji: "📐",
    progress: 45,
    total_xp: 500,
  },
  {
    id: "2",
    title: "Biology Fundamentals",
    subject: "Science",
    difficulty: "Beginner",
    instructor_name: "Mr. Cruz",
    emoji: "🔬",
    progress: 20,
    total_xp: 500,
  },
  {
    id: "3",
    title: "English Literature",
    subject: "English",
    difficulty: "Advanced",
    instructor_name: "Ms. Garcia",
    emoji: "📚",
    progress: 80,
    total_xp: 500,
  },
  {
    id: "4",
    title: "World History",
    subject: "History",
    difficulty: "Beginner",
    instructor_name: "Mr. Reyes",
    emoji: "🌍",
    progress: 10,
    total_xp: 500,
  },
  {
    id: "5",
    title: "Physics Essentials",
    subject: "Science",
    difficulty: "Advanced",
    instructor_name: "Dr. Tan",
    emoji: "⚛️",
    progress: 60,
    total_xp: 500,
  },
  {
    id: "6",
    title: "Creative Writing",
    subject: "English",
    difficulty: "Intermediate",
    instructor_name: "Ms. Lim",
    emoji: "✍️",
    progress: 35,
    total_xp: 500,
  },
];

export const demoModules = [
  { id: "m1", title: "Introduction to Linear Equations", xp_reward: 100, description: "Learn how equations represent balanced relationships and how to read them." },
  { id: "m2", title: "Solving One-Step Equations", xp_reward: 150, description: "Practice isolating variables using inverse operations." },
  { id: "m3", title: "Applied Problems", xp_reward: 200, description: "Translate word problems into equations and solve them step by step." },
  { id: "m4", title: "Advanced Theory", xp_reward: 250, description: "Explore more complex equation structures and interpretation." },
  { id: "m5", title: "Final Challenge", xp_reward: 300, description: "This capstone module will open after your professor releases it." },
  { id: "m6", title: "Extension Problems", xp_reward: 320, description: "Locked for now until the class reaches the extension track." },
];

const buildModuleSequence = ({
  topic,
  imageA,
  imageB,
  quizPromptA,
  quizPromptB,
  finalPrompt,
  correctA,
  correctB,
  finalAnswers,
}) => ([
  {
    id: "lesson-1",
    type: "lesson",
    section: "Lesson 1",
    title: `${topic}: What it means`,
    subtitle: "Start with the concept before solving anything.",
    body: [
      `${topic} is easiest to understand when you think about balance. Whatever happens on one side must be reflected on the other side.`,
      "In class, this usually appears as a short explanation page before students try any questions. The goal is to make the idea feel familiar first.",
    ],
    highlights: [
      "Read the equation as a relationship, not just a computation.",
      "Look for the unknown part and the known part.",
      "Keep both sides balanced while solving.",
    ],
    image: imageA,
    imageCaption: "Visual explanation card",
  },
  {
    id: "quiz-1",
    type: "quiz",
    stage: "Practice Check",
    title: "Quick check",
    prompt: quizPromptA,
    explanation: "Nice work. These quick checks help students confirm the concept before moving on.",
    options: ["The relationship stays balanced", "The numbers disappear", "The variable changes sides automatically", "The expression becomes a graph"],
    correct: correctA,
    xpReward: 20,
  },
  {
    id: "lesson-2",
    type: "lesson",
    section: "Lesson 2",
    title: `${topic}: Worked example`,
    subtitle: "See the process in action with a guided walkthrough.",
    body: [
      "A worked example breaks the topic into small moves so the learner can follow each decision with less pressure.",
      "This is where NetAcad-style modules usually combine short text, a diagram, and an interpretation of why each step matters.",
    ],
    highlights: [
      "Identify the operation attached to the variable.",
      "Use the inverse operation to undo it.",
      "Check the result by substituting it back.",
    ],
    image: imageB,
    imageCaption: "Step-by-step worked example",
  },
  {
    id: "quiz-2",
    type: "quiz",
    stage: "Practice Check",
    title: "Try another one",
    prompt: quizPromptB,
    explanation: "Checkpoint quizzes between lesson pages keep the module interactive and make the final quiz feel fair.",
    options: ["Add 5 to both sides", "Subtract 5 from both sides", "Multiply both sides by 5", "Divide both sides by 5"],
    correct: correctB,
    xpReward: 20,
  },
  {
    id: "lesson-3",
    type: "lesson",
    section: "Final Review",
    title: `${topic}: Before the final quiz`,
    subtitle: "A short summary page to reinforce the important ideas.",
    body: [
      "Before the final assessment, learners benefit from one compact review page that summarizes the technique and common mistakes.",
      "This keeps the flow close to a real module format instead of jumping from one big wall of text straight into a graded quiz.",
    ],
    highlights: [
      "Keep the equation balanced at every step.",
      "Use inverse operations carefully.",
      "Check your final answer when possible.",
    ],
    image: imageA,
    imageCaption: "Review snapshot",
  },
  {
    id: "final-quiz",
    type: "quiz",
    stage: "Final Module Quiz",
    title: "Module final quiz",
    prompt: finalPrompt,
    explanation: "That wraps the module. Final quizzes check whether the lesson pages and practice checkpoints stuck.",
    options: finalAnswers,
    correct: 1,
    xpReward: 40,
    isFinal: true,
  },
]);

export const demoModuleSequences = {
  m1: buildModuleSequence({
    topic: "Linear equations",
    imageA: "/illustrations/module-concept.svg",
    imageB: "/illustrations/module-practice.svg",
    quizPromptA: "What should stay true while solving an equation?",
    quizPromptB: "For x + 5 = 11, what is the best first step?",
    finalPrompt: "If 2x + 8 = 20, what is x?",
    correctA: 0,
    correctB: 1,
    finalAnswers: ["4", "6", "8", "12"],
  }),
  m2: buildModuleSequence({
    topic: "One-step equations",
    imageA: "/illustrations/module-concept.svg",
    imageB: "/illustrations/module-practice.svg",
    quizPromptA: "What operation helps isolate the variable first?",
    quizPromptB: "For x - 7 = 9, what should you do?",
    finalPrompt: "Solve x / 4 = 3.",
    correctA: 0,
    correctB: 0,
    finalAnswers: ["7", "12", "16", "1"],
  }),
  m3: buildModuleSequence({
    topic: "Word problems",
    imageA: "/illustrations/module-review.svg",
    imageB: "/illustrations/module-practice.svg",
    quizPromptA: "What is the first thing to identify in a word problem?",
    quizPromptB: "Which action best helps turn a sentence into an equation?",
    finalPrompt: "A number plus 8 equals 21. What is the number?",
    correctA: 0,
    correctB: 0,
    finalAnswers: ["11", "13", "21", "29"],
  }),
};
